### ISSUE TITLE
Why doesn't the http.ResposeWriter implement http.Flush

### ISSUE THREAD

**Issue by lucat1** [kataras/muxie#8]
Given this test function:
```go
func test(w http.ResponseWriter, r *http.Request) {
	_, ok := w.(http.Flusher)
	fmt.Println(ok)
}
```

This returns true:
```go
func main() {
	http.ListenAndServe(":8080", http.HandlerFunc(test))
}
```

This returns false:

```go
func main() {
	mux := muxie.NewMux()
	mux.HandleFunc("/*path", test)
	http.ListenAndServe(":8080", mux)
}
```

Is there any reason why the `http.RequestWriter` does not implement `http.Flusher`? I absolutely need this feature for my usage of the router

@kataras

**Comment by kataras** [comment]
Hello @lucat1,

Sorry for the delay and the issue, it has been resolved. Please upgrade to `v1.0.8`.
